version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3456:3456"
    volumes:
      - ./content:/usr/src/app/content
      - ./public:/usr/src/app/public
    command: ["npx", "quartz", "build", "--serve", "--port", "3456"]


