# Install nginx and place in /etc/nginx/sites-enabled/quartz
server {
    listen 80;
    server_name <domain_name>;
    root /home/vadmin/services/quartz-hoster/public;
    index index.html;
    error_page 404 /404.html;

    location / {
        try_files $uri $uri.html $uri/ =404;
        # Force correct content type for extensionless HTML in iframes
        types {
            text/html html;
            image/svg+xml svg svgz;
        }
        default_type text/html;
    }
}